[0m15:16:51.699557 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10968d1c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b496630>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b496300>]}


============================== 15:16:51.703524 | e8ffbd0a-c867-4a35-92e6-5529659ffcf7 ==============================
[0m15:16:51.703524 [info ] [MainThread]: Running with dbt=1.8.4
[0m15:16:51.704002 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/Users/benjaminsicard/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt init dbt-paris2024', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:16:54.671917 [error] [MainThread]: Encountered an error:

[0m15:16:54.678045 [error] [MainThread]: Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/dbt/cli/requires.py", line 138, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/dbt/cli/requires.py", line 101, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/dbt/cli/main.py", line 470, in init
    results = task.run()
              ^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/dbt/task/init.py", line 325, in run
    project_name = self.get_valid_project_name()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/dbt/task/init.py", line 279, in get_valid_project_name
    name = click.prompt("Enter a name for your project (letters, digits, underscore)")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m15:16:54.695537 [debug] [MainThread]: Resource report: {"command_name": "init", "command_wall_clock_time": 3.0579798, "process_user_time": 0.675109, "process_kernel_time": 0.170507, "process_mem_max_rss": "100564992", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m15:16:54.696105 [debug] [MainThread]: Command `dbt init` failed at 15:16:54.696032 after 3.06 seconds
[0m15:16:54.696387 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109ae06e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107d02ea0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b4f9fd0>]}
[0m15:16:54.696647 [debug] [MainThread]: Flushing usage events
